backend:
  name: git-gateway
  repo: kavaktalha/talatalareads
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Yazıları"
    folder: "_posts"
    create: true
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime"}
      - {label: "İçerik", name: "body", widget: "markdown"}
